inherit_from: configs/ScanNet/scannet.yaml
mode: rgbd
mapping:
  device: "cuda:0"
  bound: [[-1.5 ,15.0], [-0.5, 15.0], [-8.0, 3.5]]
  marching_cubes_bound: [[-1.5, 15.0], [-0.5, 15.0], [-8.0, 3.0]]
  keyframe_every: 5
grid:
  hash_size: 16


tracking:
  frontend:
    enable_loop: True

meshing:
  gt_mesh_path: './ScanNet/scene0054_00/scene0054_00_vh_clean.ply'



data:

  datadir: ./scene0054_00
  trainskip: 1
  output: output/scannet/scene0054_00
  exp_name: demo

